spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/conclave_db
    username: conclave_user
    password: conclave_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
